apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lens-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lens-prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: lens-metrics
